apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: rollouts-demo-pipeline
description: Delivery pipeline for rollouts-demo application
serialPipeline:
  stages:
  - targetId: production
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production GKE cluster
gke:
  cluster: projects/${PROJECT_ID}/locations/us-central1/clusters/autopilot-cluster-1
