apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-analysis-ai-agent
spec:
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result > 0.50
      provider:
        plugin:
          argoproj-labs/metric-ai:
            # Use agent mode - agent fetches logs using its own tools
            analysisMode: agent
            # Pod selectors for agent to fetch logs
            stableLabel: role=stable
            canaryLabel: role=canary
            # Required: Agent URL (must be explicitly configured)
            agentUrl: http://kubernetes-agent.argo-rollouts.svc.cluster.local:8080
            # Optional: Create GitHub issues on canary failures
            githubUrl: https://github.com/carlossg/rollouts-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-analysis-ai
spec:
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result > 0.50
      provider:
        plugin:
          argoproj-labs/metric-ai:
            # Use default mode (inline mode)
            analysisMode: default
            stablePodLabel: role=stable
            canaryPodLabel: role=canary
            model: gemini-2.0-flash
            githubUrl: https://github.com/carlossg/rollouts-demo
            extraPrompt: |
              Ignore color changes.
